version: '3'

services:
  fitness_pg:
    image: postgres:14
    container_name: fitness_pg
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    env_file: .env.production
  fitness_api:
    container_name: fitness_api
    build:
      context: .
      dockerfile: ./Dockerfile.production
    ports:
      - 8080:8080
    depends_on:
      - fitness_pg
    env_file: .env.production
volumes:
  db-store: